modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="better_cobble_gen"
version="1.3"
displayName="Better Cobble Gen"
credits=""
displayURL="https://github.com/besser435/Better-Cobble-Generation"
authors="brandonusa"
description='''
A Create addon for better cobble generation recipes.
'''

[[dependencies.better_cobble_gen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.better_cobble_gen]]
    modId="create"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


